services:
  - type: web
    name: forzer-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: SETUP_KEY
        sync: false
        generateValue: true
